[package]
name = "cr-cli"
version.workspace = true
edition.workspace = true

[dependencies]
cr-core.workspace = true
cr-io.workspace = true
cr-image.workspace = true
anyhow.workspace = true
serde_json.workspace = true
clap.workspace = true
sha1.workspace = true
tar.workspace = true
zip.workspace = true

[lints]
workspace = true

