[package]
name = "cr-io"
version.workspace = true
edition.workspace = true

[dependencies]
cr-core.workspace = true
cr-image.workspace = true
thiserror.workspace = true
zip.workspace = true
tar.workspace = true
sha1.workspace = true
xattr.workspace = true
pdfium-render = "0.8"
jpeg-encoder = "0.6"

[lints]
workspace = true
