[package]
name = "cr-engine"
version.workspace = true
edition.workspace = true

[dependencies]
cr-core = { path = "../cr-core" }
cr-io = { path = "../cr-io" }
cr-image = { path = "../cr-image" }
zip.workspace = true
chrono.workspace = true
fancy-regex = "0.14"
notify = "6"

[lints]
workspace = true

[dev-dependencies]
zip = "2"
