//! T2 gate: every resx PNG name resolves to its exact asset
//! file; the GIF/ICO names stay unresolvable (not bundled); the
//! `#variant` suffix falls back to the base name. The table is
//! generated from `ComicRack/Properties/Resources.resx` (230
//! ResXFileRef entries, 2026-09-04) and mirrors the C# name →
//! file mapping verbatim.

use cr_ui::icon::path_for_name;

/// All 212 resx PNG names with their mapped asset paths
/// (relative to the icons root).
const PNGS: &[(&str, &str)] = &[
    ("AddFavorites", "AddFavorites.png"),
    ("AddFolder", "AddFolder.png"),
    ("AddList", "AddList.png"),
    ("AddListFavorites", "AddListFavorites.png"),
    ("AddTab", "AddTab.png"),
    ("AdvancedPref", "AdvancedPref.png"),
    ("ArrowDown", "ArrowDown.png"),
    ("ArrowRight", "ArrowRight.png"),
    ("AutoRotate", "AutoRotate.png"),
    ("BackgroundJob", "BackgroundJob.png"),
    ("Backup", "Backup.png"),
    ("BehaviorPref", "BehaviorPref.png"),
    ("Bookmark", "Bookmark.png"),
    ("BrowseNext", "BrowseNext.png"),
    ("BrowsePrevious", "BrowsePrevious.png"),
    ("Browser", "Browser.png"),
    ("Clock", "Clock.png"),
    ("Close", "Close.png"),
    ("ComicPage", "ComicPage.png"),
    ("ComicRackApp256", "ComicRackApp256.png"),
    ("Copy", "Copy.png"),
    ("CursorScroll", "CursorScroll.png"),
    ("Cut", "Cut.png"),
    ("DarkArrowDown", "Dark/ArrowDown.png"),
    ("DarkArrowRight", "Dark/ArrowRight.png"),
    ("DarkDetailView", "Dark/DetailView.png"),
    ("DarkDoubleArrow", "Dark/DoubleArrow.png"),
    ("DarkEditDelete", "Dark/EditDelete.png"),
    ("DarkGapDown", "Dark/GapDown.png"),
    ("DarkGapUp", "Dark/GapUp.png"),
    ("DarkGapUpDown", "Dark/GapUpDown.png"),
    ("DarkGoFirst", "Dark/GoFirst.png"),
    ("DarkGoLast", "Dark/GoLast.png"),
    ("DarkGoNext", "Dark/GoNext.png"),
    ("DarkGoPrevious", "Dark/GoPrevious.png"),
    ("DarkGroup", "Dark/Group.png"),
    ("DarkGroupDown", "Dark/GroupDown.png"),
    ("DarkGroupUp", "Dark/GroupUp.png"),
    ("DarkLocked", "Dark/Locked.png"),
    ("DarkRename", "Dark/Rename.png"),
    ("DarkRenumber", "Dark/Renumber.png"),
    ("DarkSmallArrowDown", "Dark/SmallArrowDown.png"),
    ("DarkSmallArrowRight", "Dark/SmallArrowRight.png"),
    ("DarkSmallCloseGray", "Dark/SmallCloseGray.png"),
    ("DarkSort", "Dark/Sort.png"),
    ("DarkSortDown", "Dark/SortDown.png"),
    ("DarkSortUp", "Dark/SortUp.png"),
    ("DarkStarWhite", "Dark/StarWhite.png"),
    ("DarkStarWhiteHollow", "Dark/StarWhiteHollow.png"),
    ("DarkThumbView", "Dark/ThumbView.png"),
    ("DarkTileView", "Dark/TileView.png"),
    ("DarkZoomClear", "Dark/ZoomClear.png"),
    ("DataSourceConnected", "DataSourceConnected.png"),
    ("DataSourceDisconnected", "DataSourceDisconnected.png"),
    ("Database", "Database.png"),
    ("Deleted", "Deleted.png"),
    ("DetailView", "DetailView.png"),
    ("DeviceSync", "DeviceSync.png"),
    ("DeviceSyncError", "DeviceSyncError.png"),
    ("DisplaySettings", "DisplaySettings.png"),
    ("DoubleArrow", "DoubleArrow.png"),
    ("EditClear", "EditClear.png"),
    ("EditCopy", "EditCopy.png"),
    ("EditDelete", "EditDelete.png"),
    ("EditDevices", "EditDevices.png"),
    ("EditPaste", "EditPaste.png"),
    ("EditSearchDocument", "EditSearchDocument.png"),
    ("ExpandCollapseAll", "ExpandCollapseAll.png"),
    ("Export", "Export.png"),
    ("ExportError", "ExportError.png"),
    ("Favorites", "Favorites.png"),
    ("FilelessMarker", "FilelessMarker.png"),
    ("FitAll", "FitAll.png"),
    ("FitBest", "FitBest.png"),
    ("FitHeight", "FitHeight.png"),
    ("FitRotate", "FitRotate.png"),
    ("FitWidth", "FitWidth.png"),
    ("FitWidthAdaptive", "FitWidthAdaptive.png"),
    ("FullScreen", "FullScreen.png"),
    ("GapDown", "GapDown.png"),
    ("GapUp", "GapUp.png"),
    ("GapUpDown", "GapUpDown.png"),
    ("GaugesAll", "GaugesAll.png"),
    ("GaugesNew", "GaugesNew.png"),
    ("GaugesTotal", "GaugesTotal.png"),
    ("GaugesUnread", "GaugesUnread.png"),
    ("GetInfo", "GetInfo.png"),
    ("GoFirst", "GoFirst.png"),
    ("GoLast", "GoLast.png"),
    ("GoNext", "GoNext.png"),
    ("GoPrevious", "GoPrevious.png"),
    ("GrayLight", "GrayLight.png"),
    ("GreenLight", "GreenLight.png"),
    ("Group", "Group.png"),
    ("GroupDown", "GroupDown.png"),
    ("GroupUp", "GroupUp.png"),
    ("Heart", "Heart.png"),
    ("Help", "Help.png"),
    ("IncludeSubFolders", "IncludeSubFolders.png"),
    ("InfoPanel", "InfoPanel.png"),
    ("Keyboard", "Keyboard.png"),
    ("LastMarker", "LastMarker.png"),
    ("Library", "Library.png"),
    ("LibraryPref", "LibraryPref.png"),
    ("List", "List.png"),
    ("ListLayout", "ListLayout.png"),
    ("Locked", "Locked.png"),
    ("MenuToggle", "MenuToggle.png"),
    ("Minus", "Minus.png"),
    ("Network", "Network.png"),
    ("NewBookmark", "NewBookmark.png"),
    ("NewList", "NewList.png"),
    ("NewSearchDocument", "NewSearchDocument.png"),
    ("NewSearchFolder", "NewSearchFolder.png"),
    ("NewTab", "NewTab.png"),
    ("NewWindow", "NewWindow.png"),
    ("News", "News.png"),
    ("Next", "Next.png"),
    ("NextBookmark", "NextBookmark.png"),
    ("NextFromList", "NextFromList.png"),
    ("NotValidated", "NotValidated.png"),
    ("NumberFrame", "NumberFrame.png"),
    ("Open", "Open.png"),
    ("OpenMarker", "OpenMarker.png"),
    ("Original", "Original.png"),
    ("Oversized", "Oversized.png"),
    ("Package", "Package.png"),
    ("Page", "Page.png"),
    ("Pin", "Pin.png"),
    ("Preferences", "Preferences.png"),
    ("PrevFromList", "PrevFromList.png"),
    ("Previous", "Previous.png"),
    ("PreviousBookmark", "PreviousBookmark.png"),
    ("RandomComic", "RandomComic.png"),
    ("RatingBlue", "RatingBlue.png"),
    ("RatingYellow", "RatingYellow.png"),
    ("ReaderPref", "ReaderPref.png"),
    ("RedExclamation", "RedExclamation.png"),
    ("Redo", "Redo.png"),
    ("Refresh", "Refresh.png"),
    ("RefreshThumbnail", "RefreshThumbnail.png"),
    ("RemoteDatabase", "RemoteDatabase.png"),
    ("RemoteDatabaseLocked", "RemoteDatabaseLocked.png"),
    ("RemoteDatabaseLocked1", "RemoteDatabaseLocked1.png"),
    ("RemoveBookmark", "RemoveBookmark.png"),
    ("Rename", "Rename.png"),
    ("Renumber", "Renumber.png"),
    ("Restart", "Restart.png"),
    ("RevealExplorer", "RevealExplorer.png"),
    ("RightToLeft", "RightToLeft.png"),
    ("Rotate0", "Rotate0.png"),
    ("Rotate0Permanent", "Rotate0Permanent.png"),
    ("Rotate180", "Rotate180.png"),
    ("Rotate180Permanent", "Rotate180Permanent.png"),
    ("Rotate270", "Rotate270.png"),
    ("Rotate270Permanent", "Rotate270Permanent.png"),
    ("Rotate90", "Rotate90.png"),
    ("Rotate90Permanent", "Rotate90Permanent.png"),
    ("RotateLeft", "RotateLeft.png"),
    ("RotateRight", "RotateRight.png"),
    ("Save", "Save.png"),
    ("Scan", "Scan.png"),
    ("Screenshot", "Screenshot.png"),
    ("ScriptingPref", "ScriptingPref.png"),
    ("Search", "Search.png"),
    ("SearchDocument", "SearchDocument.png"),
    ("SearchFolder", "SearchFolder.png"),
    ("SharingPref", "SharingPref.png"),
    ("Sidebar", "Sidebar.png"),
    ("SinglePage", "SinglePage.png"),
    ("SinglePageRtl", "SinglePageRtl.png"),
    ("SmallArrowDown", "SmallArrowDown.png"),
    ("SmallArrowRight", "SmallArrowRight.png"),
    ("SmallClose", "SmallClose.png"),
    ("SmallCloseGray", "SmallCloseGray.png"),
    ("SmallPreview", "SmallPreview.png"),
    ("Sort", "Sort.png"),
    ("SortDown", "SortDown.png"),
    ("SortUp", "SortUp.png"),
    ("Splash", "Splash.png"),
    ("Stacking", "Stacking.png"),
    ("Star", "Star.png"),
    ("StarBlack", "StarBlack.png"),
    ("StarBlackHollow", "StarBlackHollow.png"),
    ("StarBlue", "StarBlue.png"),
    ("StarSmall", "StarSmall.png"),
    ("StarYellow", "StarYellow.png"),
    ("SyncBrowser", "SyncBrowser.png"),
    ("TempFolder", "TempFolder.png"),
    ("ThumbView", "ThumbView.png"),
    ("TileView", "TileView.png"),
    ("Tools", "Tools.png"),
    ("TwoPage", "TwoPage.png"),
    ("TwoPageAutoscroll", "TwoPageAutoscroll.png"),
    ("TwoPageForced", "TwoPageForced.png"),
    ("TwoPageForcedRtl", "TwoPageForcedRtl.png"),
    ("TwoPageRtl", "TwoPageRtl.png"),
    ("Undo", "Undo.png"),
    ("UndockReader", "UndockReader.png"),
    ("UpdateBig", "UpdateBig.png"),
    ("UpdateSmall", "UpdateSmall.png"),
    ("UpdateWeb", "UpdateWeb.png"),
    ("Validated", "Validated.png"),
    ("View", "View.png"),
    ("ViewOptions", "ViewOptions.png"),
    ("WebBlog", "WebBlog.png"),
    ("WebForum", "WebForum.png"),
    ("Workspace", "Workspace.png"),
    ("Zoom", "Zoom.png"),
    ("ZoomClear", "ZoomClear.png"),
    ("ZoomIn", "ZoomIn.png"),
    ("ZoomOut", "ZoomOut.png"),
    // About is a GIF in the C# resx; the still frame ships as PNG
    // (the T3 Help menu icon consumer).
    ("About", "About.png"),
];

const NOT_BUNDLED: &[&str] = &[
    "AlignBottom",
    "AlignFill",
    "AlignLeft",
    "AlignRight",
    "BigBallAnimation",
    "ComicRackAppSmall",
    "DeviceSyncAnimation",
    "DeviceSyncAnimationWithError",
    "ExportAnimation",
    "ExportAnimationWithError",
    "FileBrowser",
    "ReadInfoAnimation",
    "ReadPagesAnimation",
    "ScanAnimation",
    "SmallBallAnimation",
    "UpdateInfoAnimation",
    "UpdatePages",
];

#[test]
fn every_resx_png_resolves_to_its_asset() {
    assert_eq!(PNGS.len(), 213);
    for (name, file) in PNGS {
        let path =
            path_for_name(name).unwrap_or_else(|| panic!("resx PNG name {name} did not resolve"));
        let expected = std::path::Path::new(file);
        assert!(
            path.ends_with(expected),
            "name {name}: expected …/{file}, got {}",
            path.display()
        );
    }
}

#[test]
fn gif_and_ico_names_stay_unresolved() {
    assert_eq!(NOT_BUNDLED.len(), 17);
    for name in NOT_BUNDLED {
        assert!(
            path_for_name(name).is_none(),
            "{name} must not resolve (GIF/ICO assets are not bundled)"
        );
    }
}

#[test]
fn hash_variants_fall_back_to_the_base_name() {
    let base = path_for_name("Open").expect("Open resolves");
    let variant = path_for_name("Open#Disabled").expect("#variant falls back");
    assert_eq!(base, variant);
    assert!(path_for_name("#").is_none());
    assert!(path_for_name("NoSuchIcon").is_none());
}
